### ISSUE TITLE
Footer - Cambio de títulos de las pestañas

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/cygnus#15]
Por favor cambiarlas así: 
1. "Sobre este portal" en vez de "Red de socios."
2. "Términos y condiciones" en vez de "Términos de uso"

**Comment by valegrajales** [comment]
Fixed in 24e1f81a251c78598ab2f12fc68c36e88a0a7501

**Comment by javiesgm** [comment]
Valentina, ¿me puedes ayudar con esto?
El texto que va en "Sobre este portal" es el siguiente: 

"El Catálogo de la Biodiversidad de Colombia recopila información sobre las especies de fauna y flora que habitan en nuestro país. Está diseñado para ser una herramienta colaborativa en la que participen la mayor cantidad posible de organizaciones y personas, con el fin de tener la más completa red de información sobre la biodiversidad que sea de acceso libre y que ayude a la construcción de una sociedad sostenible, consciente e informada."

**Comment by valegrajales** [comment]
Fixed in ea0e7b9993b68c3efc0da4c084e562b07be59509
