### ISSUE TITLE
Actualización de favicon

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/cygnus#17]
La idea es sustituir el favicon actual por los que van adjuntos mientras se desarrolla el logo del catálogo. 

![favicon-16x16](https://cloud.githubusercontent.com/assets/14220404/12980321/f9f875a4-d0a9-11e5-9ab7-fa5e4d0fb729.png)
![favicon-32x32](https://cloud.githubusercontent.com/assets/14220404/12980319/f9c80c34-d0a9-11e5-90b1-98909cdd9051.png)
![favicon-96x96](https://cloud.githubusercontent.com/assets/14220404/12980320/f9e6ba94-d0a9-11e5-9f96-519cd92e3e79.png)

**Comment by valegrajales** [comment]
Fixed in f6ea39944c44adeb70490b2d919a1949325f9e54
