### ISSUE TITLE
Barra de busqueda

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#18]
Eliminar el marco y su efecto.
![captura de pantalla 2016-02-11 a las 10 31 17 a m](https://cloud.githubusercontent.com/assets/11927544/12980595/1aa8e760-d0ab-11e5-8c2a-436d2ec25c49.png)

**Comment by valegrajales** [comment]
Fixed in 72ce4ede63e6e47e466e12577171f0a3a1460d34
