### ISSUE TITLE
Inconsistencies between mockups and biodiversidad.co site

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/cygnus#2]
Top navigation styles, list results and pagination on site are not consistent with the mockups. 
1. "Filters" text size: Should be size 18, but works on size 16 as well.  
2. Circle beneath arrow on Filters menu: There shouldn't be any circle beneath the arrow that collapses the menu.
3. "mostrando 20 de 3386 fichas" size: on the mockups is small, but would be better at size 16. 
4. Styles on list results are missing: Species, Nombre Común, taxon page id and details on taxon pages.

Site test: 
http://192.168.205.196:8000/
![captura de pantalla 2016-02-01 a las 12 13 37 p m](https://cloud.githubusercontent.com/assets/14220404/12724756/62aec064-c8dd-11e5-841a-32dcd70e54fc.png)

Mockup screenshot: 
![captura de pantalla 2016-02-01 a las 12 11 45 p m](https://cloud.githubusercontent.com/assets/14220404/12724809/9b19561c-c8dd-11e5-97e5-e76f762dd038.png)

**Comment by valegrajales** [comment]
Fixed in 3254696c39fa136c3093de1da7a257f0bc66c030

**Comment by danipilze** [comment]
should be closed?

**Comment by valegrajales** [comment]
Yes

On Thu, Feb 11, 2016 at 9:41 AM, Daniel Amariles notifications@github.com
wrote:

> should be closed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SIB-Colombia/cygnus/issues/2#issuecomment-182892334.

## 
- Valentina Grajales Olarte *Sistema de Información sobre Biodiversidad
- Instituto de Investigación de Recursos Biológicos Alexander von Humboldt
  Calle 28A No. 15-09 PBX: (57) 1 320 2767 Ext. 3107 Bogotá, D.C., Colombia*

Antes de imprimir este mensaje, piensa si realmente necesitas
hacerlo. ¡Gracias!
