### ISSUE TITLE
Eliminar el marco polaroid

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#20]
Las imágenes del preview de las fichas poseen un marco que no va con el diseño acordado. Hay que eliminarlo.
![captura de pantalla 2016-02-11 a las 10 42 22 a m](https://cloud.githubusercontent.com/assets/11927544/12980846/3685d262-d0ac-11e5-9783-e3abe1bfd09d.png)

**Comment by valegrajales** [comment]
Fixed in 72ce4ede63e6e47e466e12577171f0a3a1460d34
