### ISSUE TITLE
Map of records

### ISSUE THREAD

**Issue by nestorjal** [SIB-Colombia/cygnus#21]
The Map below distribution is continuously refreshing and the records aren't loading. Also the title "_Mapa de registros publicados_" isn't displayed. 

![captura](https://cloud.githubusercontent.com/assets/7916426/12981110/46c4b426-d0ad-11e5-89c0-505a1282551f.PNG)

**Comment by danipilze** [comment]
Google Chrome Mobile

![4d9f1bd9-7420-485f-918f-4ce2954e14a7](https://cloud.githubusercontent.com/assets/3705866/13190811/be12767e-d71c-11e5-820c-a3a98e7369a9.jpeg)

**Comment by valegrajales** [comment]
Fixed in c8259057341be85471c920db9153def853e6a206
