### ISSUE TITLE
Cursiva en ARBOL TAXONÓMICO

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#22]
Todos los nombres científicos del árbol taxonómico están en cursiva y es un error. El único nombre en cursiva debe ser el de la categoría ESPECIE y SUBESPECIE.
![captura de pantalla 2016-02-11 a las 10 55 49 a m](https://cloud.githubusercontent.com/assets/11927544/12981345/40a15724-d0ae-11e5-992a-968384080a37.png)

**Comment by valegrajales** [comment]
Fixed in 33798d2dd31987e4a9f203a7dfc7b8d93b83520a

**Comment by daiesco** [comment]
Eliminar la negrilla de la fuente color verde.
![captura de pantalla 2016-02-18 a las 10 30 24 a m](https://cloud.githubusercontent.com/assets/11927544/13148303/c31f9c16-d62a-11e5-80c8-d99cc43b6d4b.png)

**Comment by ghost** [comment]
Aprovecho para solicitar que, como habíamos hablado con @daiesco , esta sección se llame "**Jerarquía taxonómica**" en lugar de "Árbol taxonómico"

**Comment by valegrajales** [comment]
Fixed in 08b06409ca3c578ca8fb84dcfd580faf5bf3f3aa and 6907a9a5f7a5f244e1593e160ac0ce385602d49c
