### ISSUE TITLE
COLECCIONES en menú FILTRO

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#24]
En los filtros hay una categoría que se llama COLECCIONES. Por tratarse se simplemente un filtro, es necesario cambiarle el nombre. Sugiero que temporalmente se llame ECOSISTEMAS y AMENAZAS.
![captura de pantalla 2016-02-11 a las 11 00 05 a m](https://cloud.githubusercontent.com/assets/11927544/12981603/5c7d5d84-d0af-11e5-971a-7ca9619d87ef.png)

**Comment by valegrajales** [comment]
Fixed in e9cea2a1a44ccf7b92f0bcff7c8257999106981f
