### ISSUE TITLE
Términos y condiciones

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/cygnus#25]
Valentina, 

La idea es que sea una página nueva con el contenido legal que sea necesario incluir. 
Adjunto mockup 

![cbc-legal-01](https://cloud.githubusercontent.com/assets/14220404/13020688/d1d664a4-d1a4-11e5-8546-f18c7bee26f8.png)
![cbc-legal-02](https://cloud.githubusercontent.com/assets/14220404/13020689/d1fd4e84-d1a4-11e5-89c8-f7b2e8f7b05c.png)

La carpeta con esta página en HTML la envié por correo sin embargo aquí está el enlace: [https://drive.google.com/a/humboldt.org.co/folderview?id=0BzvUmB30yXXxLUR3VER1TVVyNkE&usp=sharing](url)

Mil gracias!!!

**Comment by javiesgm** [comment]
Hola Valentina, 
Este es el enlace a la página de términos y condiciones: 
http://sibcolombia.elasticbeanstalk.com/terminos-y-condiciones/

Imagino que cambiará cuando esté al aire el portal.  Pero por el momento aquí está montada. 

Gracias!

**Comment by valegrajales** [comment]
Fixed in f6ea39944c44adeb70490b2d919a1949325f9e54
