### ISSUE TITLE
Términos y Condiciones

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#26]
El wordpress no muestra la información adecuadamente.
![captura de pantalla 2016-02-18 a las 2 04 34 p m](https://cloud.githubusercontent.com/assets/11927544/13154792/b35ccaba-d648-11e5-9350-bdaf59a8007c.png)

**Comment by valegrajales** [comment]
Now cynus shows terms and conditions in a new separate page: domain/terms
