### ISSUE TITLE
Carrusel de imágenes

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#27]
Se perdió el carrusel o mosaico de imágenes en las fichas de taxones.

![captura de pantalla 2016-02-18 a las 2 06 59 p m](https://cloud.githubusercontent.com/assets/11927544/13154854/04dfd30a-d649-11e5-81cc-2a759929b9e7.png)

**Comment by valegrajales** [comment]
Fixed in 80ebfea34ba0cc644a59ee0e81918723fc0eb332
