### ISSUE TITLE
Filtros desplegados

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/cygnus#28]
Cuando se ingresa al catálogo los filtros aparecen desplegados completamente. Esto no debería pasar y debe ser decisión del usuario si los despliega o no.

![captura de pantalla 2016-02-19 a las 8 30 13 a m](https://cloud.githubusercontent.com/assets/11927544/13177100/046e63cc-d6e5-11e5-8d86-1c1693f07af9.png)

**Comment by valegrajales** [comment]
Fixed in f91fdefd610fbcc334ad4bfe3f5aa60ac2ee04ca

**Comment by daiesco** [comment]
Aun queda una categoría que sigue apareciendo desplegada. GRUPOS BIOLÓGICOS

**Comment by valegrajales** [comment]
Fixed in 6792e7aa920afbfe92f207b687c1094fd6b20ce9
