### ISSUE TITLE
Missing logos at footer

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/cygnus#30]
![806d9be7-7300-4f46-88f6-b02a60bfe1ca](https://cloud.githubusercontent.com/assets/3705866/13190827/da9c2b32-d71c-11e5-9096-fa56e65ee28f.jpeg)

**Comment by javiesgm** [comment]
Issue moved to [SIB-Colombia/portal_general_wp #75](https://github.com/SIB-Colombia/portal_general_wp/issues/75) via [**ZenHub.io**](https://www.zenhub.io/)
