### ISSUE TITLE
WTF text "fuentes certificadas"

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/cygnus#36]
certified sources????

![allep5v1j4en5y3uqlxtpchrvj1opekdpujgtsjqop7l](https://cloud.githubusercontent.com/assets/3705866/13190967/bb0affe0-d71d-11e5-8c6f-24f3a8829010.jpg)

**Comment by nestorjal** [comment]
@javiesgm the milestone is close, please check this out.

**Comment by nestorjal** [comment]
Please put this test:

_La revisión de los contenidos se realiza por la propia comunidad. Se admiten los aportes de los usuarios en general. Cualquier persona puede agregar objetos, es decir, información a través de enlaces a otras páginas web._

**Comment by jumauricio** [comment]
This does not apply for this version since we don't have the community and curators feature already, that's why we call this "fuentes certificadas". This terms and conditions are for CBC 1.3, and will be updated properly when the 2.0 version is launched.
