### ISSUE TITLE
Invisible object

### ISSUE THREAD

**Issue by nestorjal** [SIB-Colombia/cygnus#38]
There's an invisible object that doesn't allow to click on some photos:

e.g. http://52.91.25.109/fichas/3517

![screen shot 2016-02-19 at 4 00 48 pm](https://cloud.githubusercontent.com/assets/7916426/13191609/2a3daf12-d722-11e5-8df8-a9d8cf481519.png)

**Comment by valegrajales** [comment]
Fixed in c8259057341be85471c920db9153def853e6a206
